<?php

namespace Kebhub\Bundle\DocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChapitresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapitresRepository extends EntityRepository
{
}
