<?php
namespace Kebhub\Bundle\UserBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneByApiKey($apiKey)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('*')
            ->from('KebhubUserBundle:User', 'u')
            ->where('u.api_key = ' . $api_key);
            
        return $qb->getQuery();
    }
}