<?php

namespace Kebhub\Bundle\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getAllByUser($user)
	{

		$qb = $this->createQueryBuilder('p');

		$qb = $qb
			->where('p.user = :user')
			->setParameter('user', $user);
		;
		
		return $qb->getQuery()->getResult();
	}


	public function getTwitterPost($user)
	{

		$qb = $this->createQueryBuilder('p');

		$qb = $qb
			->where('p.user = :user AND p.type = :type')
			->setParameter('user', $user)
			->setParameter('type', 'twitter');
		
		return $qb->getQuery()->getResult();

	}


	public function getInstagramPost($user)
	{

		$qb = $this->createQueryBuilder('p');

		$qb = $qb
			->where('p.user = :user AND p.type = :type')
			->setParameter('user', $user)
			->setParameter('type', 'instagram');
		
		return $qb->getQuery()->getResult();

	}


	public function deleteMutlipePost($ids, $user)
	{

		$qb = $this->createQueryBuilder('p');

		$qb->delete('KebhubDashboardBundle:Post', 'p');
		$qb->andWhere('p.id IN (:ids)');
		$qb->setParameter(':ids', $ids);

		return $qb->getQuery()->getResult();

	}
	
}
